version: '2'
services:
    reactjs:
        build: reactjs/.
        command: http-server ./build/. -p 80
        depends_on:
            - loopback
        #ports:
        #    - "8001:80"
        volumes:
            - ./reactjs/:/reactjs
            - /reactjs/node_modules
        restart: always
