apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hestia
  name: hestia-reactjs-deployment
  labels:
    app: hestia-reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hestia-reactjs
  template:
    metadata:
      labels:
        app: hestia-reactjs
    spec:
      containers:
      - name: hestia-reactjs
        image: stevenluong/hestia-reactjs:v0.10
        imagePullPolicy: "Always"
        #ports:
        #- containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
